language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - coverage run    olympiades/entrainement_exo3/calcule.py
  - coverage run -a olympiades/entrainement_exo3/calcule.py 57
  - coverage run -a olympiades/entrainement_exo3/valeurs_possibles.py
  - coverage run -a olympiades/entrainement_exo3/valeurs_possibles.py 20
  - coverage run -a olympiades/entrainement_2017_exercice_4.py
  - cd fractales
  - py.test -s --cov
  - cd -
  - flake8
after_success:
  - coveralls
