language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - coverage run    entrainement_olympiades_exo3/calcule.py
  - coverage run -a entrainement_olympiades_exo3/valeurs_possibles.py
after_success:
  - coveralls
