language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - cd entrainement_olympiades_exo3
  - coverage run calcule.py
  - coverage run -a valeurs_possibles.py
after_success:
  - coveralls
