"""
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

https://projecteuler.net/problem=2
"""

fibo = [1, 2]

while True:
    c = fibo[-2] + fibo[-1]
    if c > 4000000:
        break
    fibo.append(c)

resultat = sum(i if i % 2 == 0 else 0 for i in fibo)
print(resultat)
